// buttonData.js
const buttons = [
    { id: 1, label: '1. Login', url: '/login' },
    { id: 2, label: '2. Signup', url: '/signup' },
    { id: 3, label: '3. Home-Gainers', url: '/gainers' },
    { id: 4, label: '4. Home-Losers', url: '/losers' },
    { id: 5, label: '5. Home - New Listings', url: '/newlistings' },
    { id: 6, label: '6. Home - Asset details page', url: '/asset-details' },
    { id: 7, label: '7. Home - Setting Profile', url: '/setting-profile' },
    { id: 8, label: '8. Home - Setting Wallet', url: '/setting-wallet' },
    { id: 9, label: '9. Home - Setting Verification', url: '/setting-verification' },
    { id: 10, label: '10. Market List', url: '/market-list' },
    { id: 11, label: '11. Market Grid', url: '/market-grid' },
    { id: 12, label: '12. P2P Trading', url: '/p2p-trading' },
    { id: 13, label: '13. P2P Trading - Line Chart', url: '/p2p-trading-lc' },
    { id: 14, label: '14. P2P Trading - Line Chart-2', url: '/p2p-trading-lc2' },
    { id: 15, label: '15. P2P Trading - Line Chart-3', url: '/p2p-trading-lc3' },
    { id: 16, label: '16. P2P Trading - Line Chart-Proc', url: '/p2p-trading-proc' },
    { id: 17, label: '17. Assets', url: '/assets' },
    { id: 18, label: '18. Deposit', url: '/deposit' },
    { id: 19, label: '19. Withdraw/ Transfer', url: '/withdraw-tansfer' },
    { id: 20, label: '20. Withdraw/ Transfer Confirmation', url: '/wt-confirmation' },
    { id: 21, label: '21. Buy Cryptocurrency', url: '/buy-crypto' },
    { id: 22, label: '22. Asset Tokenisation Form', url: '/asset-token' },
    { id: 23, label: '23. Asset Tokenisation Form -2', url: '/asset-token-2' },
    { id: 24, label: '24. Asset Tokenisation Form -3', url: '/asset-token-3' },
    { id: 25, label: '25. Asset Tokenisation Form -4', url: '/asset-token-4' },
    { id: 26, label: '26. Asset Tokenisation Form -5', url: '/asset-token-5' },
    { id: 27, label: '27. Delist Asset Token Form', url: '/delist-asset-token' },
    { id: 28, label: '28. Delist Asset Token Form -2', url: '/delist-asset-token-2' },
    { id: 29, label: '29. Delist Asset Token Form -3', url: '/delist-asset-token-3' },
    { id: 30, label: '30. Delist Asset Token Form -4', url: '/delist-asset-token-4' },
    { id: 31, label: '31. Customer Support', url: '/customerSupport' },
    { id: 32, label: '32. Customer Support Chat', url: '/customerSupport-chat' },
    { id: 33, label: '33. ICO Page Ongoing', url: '/ico-page-ongoing' },
    { id: 34, label: '34. ICO Page Upcoming', url: '/ico-page-upcoming' },
    { id: 35, label: '35. ICO Page Completed', url: '/ico-page-completed' },
    { id: 36, label: '36. ICO Detail Page', url: '/ico-details' },
    { id: 37, label: '37. Stake and Earn', url: '/stake-earn' },
    { id: 38, label: '38. Stake and Earn -2', url: '/stack-earn2' },
    { id: 39, label: '39. FAQs', url: '/faqs' },
    { id: 40, label: '40. Juna Blog', url: '/juna-blog  ' },
];

export default buttons;
